FROM python:3.9-slim

COPY src/requirements.txt /opt/ml/code/requirements.txt
RUN pip install --no-cache-dir -r /opt/ml/code/requirements.txt

ENV PYTHONUNBUFFERED=1
ENV PATH="/opt/ml/code:${PATH}"

COPY src/inference.py /opt/ml/code/inference.py
COPY serve /usr/local/bin/serve
RUN chmod +x /usr/local/bin/serve

WORKDIR /opt/ml/code